---
title: "Bootstrapping"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(modelr)

set.seed(1)
```

## Generate a relevant example

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 +3 * x + error
  )

sim_df_nonconst = 
  sim_df_const |> 
  mutate(
    error = error * .75 * x,
    y = 2 + 3 * x + error
  )

sim_df_const |> 
  ggplot(aes(x=x, y= y)) + geom_point()


sim_df_nonconst |> 
  ggplot(aes(x=x, y= y)) + geom_point()
```


fit some linear models

```{r}
sim_df_const |> 
  lm(y ~ x, data = _) |> 
  broom::tidy()

sim_df_nonconst |> 
  lm(y ~ x, data = _) |> 
  broom::tidy()
```

## Draw and analyze a bootstrap sample

Start with function 

```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}
```

How does this work?

```{r}
sim_df_nonconst |> 
  boot_sample() |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = 0.5) + 
  stat_smooth(method = "lm")
```

## Draw a lot of samples and analyze them

```{r Keeping Track}

boot_straps = 
  tibble(strap_number = 1:2500) |> 
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(sim_df_nonconst))
  )

boot_straps |> 
  pull(strap_sample) |>
  nth(1) |> 
  arrange(x)

```

Now we need a lm fit function for all the iterated results

```{r}
boot_results =
  boot_straps |> 
  mutate(
    models = map(strap_sample, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)) |> 
  select(strap_number, results) |> 
  unnest(results)
```

Summarizing these results to get a boostrap standard error (SE)

```{r}
boot_results |> 
  group_by(term) |> 
  summarize(
    se = sd(estimate)
  )
```

look at distribution

```{r}
boot_results |> 
  filter(term == "x") |> 
  ggplot(aes(x = estimate)) + 
  geom_density()
```

Can I construct a CI

```{r}
boot_results |> 
  group_by(term) |> 
  summarize(
    ci_lower = quantile(estimate, 0.25),
    ci_upper = quantile(estimate, 0.75),
  )
```

