---
title: "Cross Validation"
output: github_document
---

```{r}
library(tidyverse)
library(tidyverse)
library(modelr)
library(mgcv)
set.seed(1)
```
Start with base simulatged data called "Training Data"
```{r Training Data}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

Do the train / test split

```{r}
train_df = sample_n(nonlin_df, 80)
test_df= anti_join(nonlin_df, train_df, by = "id")
```

```{r}
train_df |> 
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  geom_point(data = test_df, color = 'red')
```


```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```

Quick visualization of the linear model

```{r}
train_df |> 
  modelr::add_predictions(wiggly_mod) |> 
  ggplot(aes(x=x, y=y)) +
  geom_point() +
  geom_line(aes(y = pred))
```

Root Mean Squared Error

```{r}
rmse(linear_mod, train_df)
rmse(smooth_mod, train_df)
rmse(wiggly_mod, train_df)

#The lower predictive accuary value, the greatest fit 
#wiggly model is a brute force

rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)

#Across both rmse tests the smooth_mod is consistently low 
```

